routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/marie', "MarieController@test_function");


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('items', 'ItemController');

Route::resource('users', 'UserController');
Route::get ('/users/todo/{user}', 'UserController@todo')->name('users.todo');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'content', 'user_id',
    ];

    protected function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected function items()
    {
        return $this->hasMany('App\Item');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Item;
use App\User;
use Illuminate\Http\Request;
use App\Services\ItemService;
use App\Http\Requests\EditItemRequest;
use App\Http\Requests\StoreItemRequest;

class ItemController extends Controller
{
    private $items;

    public function __construct(ItemService $itemService)
    {
        $this->items = $itemService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('items.index')->withItems($this->items->all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all() ;
        return view("items.create")->withUsers($users);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreItemRequest $request)
    {
        $this->items->create($request->all(['content','user_id']));
        return redirect()->route('items.index')->with('flash', [
            'type' => 'success',
            'message' => 'Item créé avec succès !'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        $users = User::all() ;
        return view("items.update")->withItem($item)->withUsers($users);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(EditItemRequest $request, Item $item)
    {
        $this->items->update($item, $request->all(['content', 'user_id']));
        return redirect()->route('items.index')->with('flash', [
            'type' => 'success',
            'message' => 'Item modifié avec succès !'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        if ($this->items->delete($item))
            return redirect()->route('items.index')->with('flash', [
            'type' => 'success',
            'message' => 'Item supprimé avec succès !'
        ]);
        else
            return redirect()->route('items.index')->with('flash', [
            'type' => 'danger',
            'message' => 'Une erreur est survenue'
        ]);
    }
}

app/Http/Controllers/MarieController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Item;

class MarieController extends Controller
{
    public function test_function(){
        $tableau = [
        ["nom" => "nico"],
        ["nom" => "marie"],
        ["nom" => "mikael"],
        ["nom" => "yousra"],
        ] ;

        $name="coucou";
//        return view('marie')->withName($name);
        return view('marie', ['name' => $tableau, 'status'=> "nul", 'items'=> Item::all()]);
        // return view('marie')->with('name', $name);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Services\UserService;
use App\User;
use App\Item;
use Illuminate\Http\Request;

class UserController extends Controller
{
    private $users;
    public function __construct(UserService $userService)
    {
        $this->users = $userService;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('users.index')->withUsers($this->users->all());
    }

    /**
     * Display a listing of the items of the users.
     *
     * @return \Illuminate\Http\Response
     */
    public function todo(User $user)
    {
        dd(Item::all());
        return "salut";
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/items/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="panel panel-default col-lg-8 col-lg-offset-2">
            <div class="panel-header">
                <h2>Créer un nouvel item</h2>
                <hr>
            </div>
            <div class="panel-body">
                <form class="horizontal-form" method="POST" action="{{ route('items.store') }}">
                {{ csrf_field() }}
                <div class="form-group{{ $errors->has('content') ? ' has-error' : ''}}">
                    <label for="content" class="control-label col-sm-2">{{ ucfirst(__('validation.attributes')['content']) }}</label>
                    <div class="col-sm-10">
                        <input class="form-control" type="text" id="content" name="content" autofocus value="{{ old('content') }}">
                    @if($errors->has('content'))
                        <span class="help-block">{{ $errors->first('content') }}</span>
                    @endif
                    </div>
                    <br><br>
                    <label for ="user" class="control-label col-sm-2">Utilisateur</label>
                    <div class="col-sm-10">
                        <select class="form-control" type="text" id="user_id" name="user_id" autofocus value="{{ old('user_id') }}">
                                <option></option>
                            @foreach($users as $user)
                                <option value="{{ $user->id }}">{{ $user->name }}</option>
                            @endforeach
                        </select>
                    @if($errors->has('content'))
                        <span class="help-block">{{ $errors->first('content') }}</span>
                    @endif
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Créer</button>
                </form>
            </div>
        </div>
    </div>
</div>



@stop

resources/views/items/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="panel panel-default col-lg-8 col-lg-offset-2">
            
            <div class="panel-header">
                <h2>
                    MES ITEMS
                    <a class="btn btn-primary btn-xs pull-right" href="{{ route('items.create') }}">
                        <i class="fa fa-plus"></i>
                        Créer
                    </a>
                </h2>
                <hr>
            </div>
            <div class="panel-body">
                @if(session('flash'))
                <div class="alert alert-{{ session('flash')['type'] }}">
                    <p>{{ session('flash')['message'] }}</p>
                </div>
                @endif
                <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Assigné à</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($items as $item)
                    <tr>
                        <td>{{ $item->content }}</td>
                        <td>{{ $item->name }}</td>
                        <td>
                            
                            <form method="POST" action="{{ route('items.destroy', ['item' => $item->id ]) }}">
                            <a class="btn btn-primary btn-xs" href="{{ route('items.edit', ['item' => $item->id ]) }}">
                                <i class="fa fa-edit"></i>
                                Modifier
                            </a>
                                {{ csrf_field() }}
                                {{ method_field("DELETE") }}
                                <button type="submit" class="btn btn-danger btn-xs">Supprimer</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@stop

resources/views/items/update.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="panel panel-default col-lg-8 col-lg-offset-2">
            <div class="panel-header">
                <h2>Modifier l'item "{{ $item->content }}"</h2>
                <hr>
            </div>
            <div class="panel-body">
                <form class="horizontal-form" method="POST" action="{{ route('items.update', ['item' => $item->id ]) }}">
                {{ csrf_field() }}
                {{ method_field("PUT") }}
                <div class="form-group{{ $errors->has('content') ? ' has-error' : ''}}">
                    <label for="content" class="control-label col-sm-2">{{ ucfirst(__('validation.attributes')['content']) }}</label>
                    <div class="col-sm-10">
                        <input class="form-control" type="text" id="content" name="content" autofocus value="{{ old('content', $item->content) }}">
                    @if($errors->has('content'))
                        <span class="help-block">{{ $errors->first('content') }}</span>
                    @endif
                    </div>
                    </br></br>
                    <label for="user_id" class="control-label col-sm-2">Utilisateur</label>
                    <div class="col-sm-10">
                        <select class="form-control" type="text" id="user_id" name="user_id" autofocus value="{{ old('user_id', $item->user_id) }}">
                            <option></option>
                            @foreach($users as $user)
                            <option  value="{{ $user->id }}" {{ $item->user_id==$user->id ? "selected" : "" }}>{{ $user->name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Modifier</button>

                </form>
            </div>
        </div>
    </div>
</div>



@stop

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @if(session('message'))
            <div class="container">
                <div class="alert alert-{{ session('message')['type'] }}">
                    <strong>{{ session('message')['title'] }}</strong>
                    <p>{{ session('message')['message'] }}</p>
                </div>
            </div>
        @endif

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/marie.blade.php
@extends('layouts.app')

@section('content')
<ul>
@foreach($name as $p)
    @if($p['nom'] == 'marie')
        <li>zzzzzzzz</li>   
    @else
        <li>{{ $p['nom'] }}</li>
    @endif
@endforeach
</ul>
<ul>
@foreach($items as $item)
        <li>{{ $item->id }} - {{ $item->content }}</li>   
@endforeach
</ul>
@stop

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="panel panel-default col-lg-8 col-lg-offset-2">
            
            <div class="panel-header">
                <h2>
                    UTILISATEURS
                    <a class="btn btn-primary btn-xs pull-right" href="{{ route('users.create') }}">
                        <i class="fa fa-plus"></i>
                        Créer
                    </a>
                </h2>
                <hr>
            </div>
            <div class="panel-body">
                <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Email</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    <tr>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>
                            
                            <form method="POST" action="{{ route('users.destroy', ['user' => $user->id ]) }}">
                                <a class="btn btn-success btn-xs" href="{{ route('users.todo', ['user' => $user->id ]) }}">
                                    <i class="fa fa-edit"></i>
                                    Voir la TODO
                                </a>
                                <a class="btn btn-primary btn-xs" href="{{ route('users.edit', ['user' => $user->id ]) }}">
                                    <i class="fa fa-edit"></i>
                                    Modifier
                                </a>
                                {{ csrf_field() }}
                                {{ method_field("DELETE") }}
                                <button type="submit" class="btn btn-danger btn-xs">Supprimer</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
                </table>
            </div>
        </div>
    </div>
</div>




@stop